image: python:3.7

before_script:
  - pip install -r requirements/requirements-dev.txt
  - python setup.py develop

stages:
  - test
  - deploy

unit-tests:
  stage: test
  script:
    - pytest --ignore=setup.py --cov=./ --cov-branch
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

integration-tests:
  stage: test
  script:
    - pytest tests/e2e/*.py

cli:
  stage: deploy
  script:
    - which llamedl
    - which llamedltagger