language: python
dist: xenial
language: python
python:
  - "3.6.7"
  - "3.7.1"
  - "3.6-dev"
  - "3.7-dev"
  - "3.8-dev"
  - "nightly"
matrix:
  allow_failures:
    python: "3.6-dev"
    python: "3.7-dev"
    python: "3.8-dev"
install:
  - pip install -r requirements/requirements-dev.txt
script:
  - pytest
  - codecov --token=6b5d0835-8dcf-4847-bc72-d2659d84dc22
  - ocular --access-token "b06798d24fa9b0d5bedc5b86a9bc6a35fb335ce48c06812e2a1c0f6006bb7707" --data-file ".coverage"