import pytest

from llame.tag_providers.musicbrainzngs_ import MusicBrainzgsTagProvider


@pytest.fixture
def musicbrainzngs_response():
    return {
        "artist-list": [
            {
                "id": "20244d07-534f-4eff-b4d4-930878889970",
                "type": "Person",
                "ext:score": "100",
                "name": "Taylor Swift",
                "sort-name": "Swift, Taylor",
                "gender": "female",
                "country": "US",
                "area": {
                    "id": "489ce91b-6658-3307-9877-795b68554c98",
                    "type": "Country",
                    "name": "United States",
                    "sort-name": "United States",
                    "life-span": {"ended": "false"},
                },
                "begin-area": {
                    "id": "0276a533-0763-47c7-956e-25e60f8e7537",
                    "type": "City",
                    "name": "Reading",
                    "sort-name": "Reading",
                    "life-span": {"ended": "false"},
                },
                "ipi-list": ["00454808047", "00454808145"],
                "isni-list": ["0000000078519858"],
                "life-span": {"begin": "1989-12-13", "ended": "false"},
                "alias-list": [
                    {
                        "locale": "ja",
                        "sort-name": "テイラー・スウィフト",
                        "type": "Artist name",
                        "primary": "primary",
                        "alias": "テイラー・スウィフト",
                    },
                    {
                        "locale": "zh_Hans_CN",
                        "sort-name": "泰勒·史薇芙特",
                        "type": "Artist name",
                        "primary": "primary",
                        "alias": "泰勒·史薇芙特",
                    },
                    {
                        "sort-name": "Swift, Taylor Alison",
                        "type": "Legal name",
                        "alias": "Taylor Alison Swift",
                    },
                ],
                "tag-list": [
                    {"count": "4", "name": "pop"},
                    {"count": "6", "name": "country"},
                    {"count": "1", "name": "electropop"},
                    {"count": "2", "name": "female vocals"},
                    {"count": "0", "name": "dance-pop"},
                    {"count": "1", "name": "pop rock"},
                    {"count": "3", "name": "country pop"},
                    {"count": "2", "name": "contemporary country"},
                    {"count": "0", "name": "teen pop"},
                    {"count": "-1", "name": "top 40"},
                    {"count": "0", "name": "country-pop"},
                    {"count": "-1", "name": "taylor-swift"},
                    {"count": "2", "name": "singer/songwriter"},
                    {"count": "-1", "name": "fixme label mess"},
                    {"count": "-1", "name": "hp"},
                ],
            },
            {
                "id": "70d19e28-9646-4009-a503-40ff75e59f49",
                "type": "Person",
                "ext:score": "52",
                "name": "Nils Sjöberg",
                "sort-name": "Sjöberg, Nils",
                "gender": "female",
                "country": "US",
                "area": {
                    "id": "489ce91b-6658-3307-9877-795b68554c98",
                    "type": "Country",
                    "name": "United States",
                    "sort-name": "United States",
                    "life-span": {"ended": "false"},
                },
                "begin-area": {
                    "id": "0276a533-0763-47c7-956e-25e60f8e7537",
                    "type": "City",
                    "name": "Reading",
                    "sort-name": "Reading",
                    "life-span": {"ended": "false"},
                },
                "disambiguation": "Taylor Swift pseudonym",
                "ipi-list": ["00804356845"],
                "life-span": {"begin": "1989-12-13", "ended": "false"},
            },
            {
                "id": "29bf395f-70bc-498a-8b86-fbe0105eb168",
                "type": "Person",
                "ext:score": "47",
                "name": "Matt Billingslea",
                "sort-name": "Billingslea, Matt",
                "gender": "male",
                "country": "US",
                "area": {
                    "id": "489ce91b-6658-3307-9877-795b68554c98",
                    "type": "Country",
                    "name": "United States",
                    "sort-name": "United States",
                    "life-span": {"ended": "false"},
                },
                "begin-area": {
                    "id": "054c7df0-85b1-4e1c-a9cd-78b30b942ea0",
                    "type": "City",
                    "name": "Westminster",
                    "sort-name": "Westminster",
                    "life-span": {"ended": "false"},
                },
                "disambiguation": "drummer for Taylor Swift",
                "life-span": {"ended": "false"},
            },
            {
                "id": "9a4eb282-6800-4ae6-b6b3-f920b6c43d5d",
                "type": "Person",
                "ext:score": "47",
                "name": "Paul Sidoti",
                "sort-name": "Sidoti, Paul",
                "gender": "male",
                "begin-area": {
                    "id": "7b2ca1e7-e7f6-4155-881d-c660a45c11e8",
                    "type": "City",
                    "name": "Cleveland",
                    "sort-name": "Cleveland",
                    "life-span": {"ended": "false"},
                },
                "disambiguation": "guitar for Taylor Swift",
                "life-span": {"begin": "1971-05-19", "ended": "false"},
            },
            {
                "id": "11fab5c6-14ba-4e45-818c-8b832fe4aa6b",
                "type": "Person",
                "ext:score": "43",
                "name": "Amos Heller",
                "sort-name": "Heller, Amos",
                "gender": "male",
                "country": "US",
                "area": {
                    "id": "489ce91b-6658-3307-9877-795b68554c98",
                    "type": "Country",
                    "name": "United States",
                    "sort-name": "United States",
                    "life-span": {"ended": "false"},
                },
                "disambiguation": "bass guitar for Taylor Swift",
                "life-span": {"begin": "1977-03-18", "ended": "false"},
                "alias-list": [
                    {
                        "sort-name": "Heller, Amos J.",
                        "type": "Legal name",
                        "alias": "Amos J. Heller",
                    }
                ],
            },
            {
                "id": "972d3f85-11fd-46d9-87ee-c7c456f874e0",
                "type": "Group",
                "ext:score": "40",
                "name": "Swift",
                "sort-name": "Swift",
                "country": "US",
                "area": {
                    "id": "489ce91b-6658-3307-9877-795b68554c98",
                    "type": "Country",
                    "name": "United States",
                    "sort-name": "United States",
                    "life-span": {"ended": "false"},
                },
                "disambiguation": "heavy metal group",
                "life-span": {"ended": "false"},
            },
            {
                "id": "38474ca4-a90f-4e40-9c57-6bd4165e9c57",
                "type": "Person",
                "ext:score": "40",
                "name": "Mike Meadows",
                "sort-name": "Meadows, Mike",
                "gender": "male",
                "begin-area": {
                    "id": "5643e356-bcd4-42ae-8e68-b75f88c347ec",
                    "type": "City",
                    "name": "Charlottesville",
                    "sort-name": "Charlottesville",
                    "life-span": {"ended": "false"},
                },
                "disambiguation": "guitar and keyboards for Taylor Swift",
                "life-span": {"ended": "false"},
            },
            {
                "id": "96d98124-88e0-40fb-bef8-b5040393d07d",
                "type": "Person",
                "ext:score": "40",
                "name": "Max Bernstein",
                "sort-name": "Bernstein, Max",
                "gender": "male",
                "disambiguation": "guitar and keyboards for Taylor Swift",
                "life-span": {"ended": "false"},
            },
            {
                "id": "f7aca70d-cd6d-4aea-a0e7-ae7427878455",
                "type": "Group",
                "ext:score": "40",
                "name": "Swift",
                "sort-name": "Swift",
                "country": "IT",
                "area": {
                    "id": "c6500277-9a3d-349b-bf30-41afdbf42add",
                    "type": "Country",
                    "name": "Italy",
                    "sort-name": "Italy",
                    "life-span": {"ended": "false"},
                },
                "disambiguation": '\'98 club duo, single "Feel Good"',
                "life-span": {"ended": "false"},
            },
            {
                "id": "59c1a64f-8041-4c5e-8d98-bffcfb78189c",
                "ext:score": "40",
                "name": "Swift",
                "sort-name": "Swift",
                "disambiguation": 'performs on "John Doe" by Shade Sheist',
                "life-span": {"ended": "false"},
            },
            {
                "id": "c5c3185e-b7d5-44f3-b583-ec1490a5bd64",
                "ext:score": "40",
                "name": "Swift",
                "sort-name": "Swift",
                "disambiguation": "Dutch? rap",
                "life-span": {"ended": "false"},
            },
            {
                "id": "9095fb7f-52f3-48d9-8dd9-eed43449d5d4",
                "ext:score": "39",
                "name": "Swift",
                "sort-name": "Swift",
                "disambiguation": "unknown Planting Seed Records artist",
                "life-span": {"ended": "false"},
            },
            {
                "id": "cf2bb133-067d-42f8-99c8-b97a1b085c24",
                "ext:score": "39",
                "name": "S.W.I.F.T.",
                "sort-name": "S.W.I.F.T.",
                "life-span": {"ended": "false"},
            },
            {
                "id": "7dea8be2-c8aa-429c-ab92-9d354d4f08dd",
                "type": "Person",
                "ext:score": "39",
                "name": "Swift",
                "sort-name": "Swift",
                "gender": "male",
                "disambiguation": "associated with Eminem",
                "life-span": {"ended": "false"},
            },
            {
                "id": "91bdf092-f31d-41b4-ae12-2be8378896e7",
                "ext:score": "39",
                "name": "Swift",
                "sort-name": "Swift",
                "disambiguation": 'featured artist on "I Want You Boy"',
                "life-span": {"ended": "false"},
            },
            {
                "id": "d02012ce-0272-46a2-990c-301b6b33ad93",
                "type": "Person",
                "ext:score": "39",
                "name": "Swift",
                "sort-name": "Swift",
                "gender": "male",
                "area": {
                    "id": "f03d09b3-39dc-4083-afd6-159e3f0d462f",
                    "type": "City",
                    "name": "London",
                    "sort-name": "London",
                    "life-span": {"ended": "false"},
                },
                "disambiguation": "Member of UK Grime group Section Boyz",
                "life-span": {"ended": "false"},
            },
            {
                "id": "b47a773c-3e27-4607-b427-b8d47db94f1f",
                "type": "Person",
                "ext:score": "39",
                "name": "Swift",
                "sort-name": "Swift",
                "gender": "male",
                "area": {
                    "id": "c920948b-83e3-40b7-8fe9-9ab5abaac55b",
                    "type": "City",
                    "name": "Houston",
                    "sort-name": "Houston",
                    "life-span": {"ended": "false"},
                },
                "disambiguation": "Houston, TX rapper",
                "life-span": {"ended": "false"},
            },
            {
                "id": "4dee83aa-8391-40ba-a627-b36710caed4c",
                "type": "Person",
                "ext:score": "39",
                "name": "Swift",
                "sort-name": "Swift",
                "disambiguation": "Engineer",
                "life-span": {"ended": "false"},
            },
            {
                "id": "dc1e5f43-4fd0-44aa-90b9-12365f5d639f",
                "type": "Group",
                "ext:score": "39",
                "name": "Swift",
                "sort-name": "Swift",
                "country": "BE",
                "area": {
                    "id": "5b8a5ee5-0bb3-34cf-9a75-c27c44e341fc",
                    "type": "Country",
                    "name": "Belgium",
                    "sort-name": "Belgium",
                    "life-span": {"ended": "false"},
                },
                "disambiguation": "Belgian group",
                "life-span": {"ended": "false"},
            },
            {
                "id": "b9a8c773-973b-4a0f-8f4e-c21775abf4c5",
                "type": "Person",
                "ext:score": "36",
                "name": "Rob Swift",
                "sort-name": "Swift, Rob",
                "gender": "male",
                "country": "US",
                "area": {
                    "id": "489ce91b-6658-3307-9877-795b68554c98",
                    "type": "Country",
                    "name": "United States",
                    "sort-name": "United States",
                    "life-span": {"ended": "false"},
                },
                "begin-area": {
                    "id": "935bd115-b4fb-4106-b804-5e8e18ef2fb0",
                    "type": "City",
                    "name": "Jackson Heights",
                    "sort-name": "Jackson Heights",
                    "life-span": {"ended": "false"},
                },
                "isni-list": ["0000000044091806"],
                "life-span": {"begin": "1972-05-14", "ended": "false"},
                "alias-list": [{"sort-name": "DJ Rob Swift", "alias": "DJ Rob Swift"}],
                "tag-list": [{"count": "1", "name": "hip hop"}],
            },
            {
                "id": "607a36bb-e965-486d-b9ae-f635ba53c1b4",
                "type": "Person",
                "ext:score": "36",
                "name": "Swift Guad",
                "sort-name": "Guad, Swift",
                "gender": "male",
                "country": "FR",
                "area": {
                    "id": "08310658-51eb-3801-80de-5a0739207115",
                    "type": "Country",
                    "name": "France",
                    "sort-name": "France",
                    "life-span": {"ended": "false"},
                },
                "life-span": {"ended": "false"},
                "tag-list": [{"count": "1", "name": "rap"}],
            },
            {
                "id": "2f20bb6a-9eb4-419c-8ec8-77446da0d466",
                "type": "Person",
                "ext:score": "36",
                "name": "Mampi Swift",
                "sort-name": "Mampi Swift",
                "gender": "male",
                "country": "GB",
                "area": {
                    "id": "8a754a16-0027-3a29-b6d7-2b40ea0481ed",
                    "type": "Country",
                    "name": "United Kingdom",
                    "sort-name": "United Kingdom",
                    "life-span": {"ended": "false"},
                },
                "life-span": {"ended": "false"},
                "alias-list": [
                    {"sort-name": "DJ Swift", "alias": "DJ Swift"},
                    {"sort-name": "Mampy Swift", "alias": "Mampy Swift"},
                    {"sort-name": "DJ Mampi", "alias": "DJ Mampi"},
                    {"sort-name": "DJ Mampi Swift", "alias": "DJ Mampi Swift"},
                ],
                "tag-list": [
                    {"count": "1", "name": "dj"},
                    {"count": "1", "name": "british"},
                    {"count": "1", "name": "dance and electronica"},
                    {"count": "1", "name": "uk"},
                    {"count": "1", "name": "production music"},
                    {"count": "1", "name": "drum n bass"},
                    {"count": "1", "name": "edm"},
                    {"count": "1", "name": "drum and bass"},
                    {"count": "1", "name": "contemporary"},
                    {"count": "1", "name": "electronic"},
                    {"count": "1", "name": "dance"},
                    {"count": "1", "name": "jungle"},
                ],
            },
            {
                "id": "3088612f-a12d-4929-9c97-c15da18788b3",
                "type": "Person",
                "ext:score": "36",
                "name": "Eddie Taylor",
                "sort-name": "Taylor, Eddie",
                "gender": "male",
                "country": "US",
                "area": {
                    "id": "489ce91b-6658-3307-9877-795b68554c98",
                    "type": "Country",
                    "name": "United States",
                    "sort-name": "United States",
                    "life-span": {"ended": "false"},
                },
                "begin-area": {
                    "id": "6fddb177-f3fc-4c30-9d49-9c7e949fe0bc",
                    "type": "Subdivision",
                    "name": "Mississippi",
                    "sort-name": "Mississippi",
                    "life-span": {"ended": "false"},
                },
                "end-area": {
                    "id": "29a709d8-0320-493e-8d0c-f2c386662b7f",
                    "type": "City",
                    "name": "Chicago",
                    "sort-name": "Chicago",
                    "life-span": {"ended": "false"},
                },
                "disambiguation": "Electric blues guitarist & singer",
                "life-span": {
                    "begin": "1923-01-29",
                    "end": "1985-12-25",
                    "ended": "true",
                },
                "alias-list": [
                    {
                        "locale": "en",
                        "sort-name": "Taylor, Eddie",
                        "type": "Artist name",
                        "primary": "primary",
                        "alias": "Eddie Taylor",
                    },
                    {
                        "locale": "en",
                        "sort-name": "Taylor, Edward",
                        "type": "Legal name",
                        "alias": "Edward Taylor",
                    },
                    {
                        "sort-name": "Eddie 'Playboy' Taylor",
                        "alias": "Eddie 'Playboy' Taylor",
                    },
                ],
            },
            {
                "id": "9ab4a3b4-3206-4c12-ac6b-50d64ca98119",
                "type": "Person",
                "ext:score": "36",
                "name": "Jonathan Swift",
                "sort-name": "Swift, Jonathan",
                "gender": "male",
                "country": "IE",
                "area": {
                    "id": "390b05d4-11ec-3bce-a343-703a366b34a5",
                    "type": "Country",
                    "name": "Ireland",
                    "sort-name": "Ireland",
                    "life-span": {"ended": "false"},
                },
                "begin-area": {
                    "id": "462e7952-4fa9-43cd-bc24-2c5c9cd5dd47",
                    "type": "City",
                    "name": "Dublin",
                    "sort-name": "Dublin",
                    "life-span": {"ended": "false"},
                },
                "end-area": {
                    "id": "462e7952-4fa9-43cd-bc24-2c5c9cd5dd47",
                    "type": "City",
                    "name": "Dublin",
                    "sort-name": "Dublin",
                    "life-span": {"ended": "false"},
                },
                "isni-list": ["0000000121214321"],
                "life-span": {
                    "begin": "1667-11-30",
                    "end": "1745-10-19",
                    "ended": "true",
                },
                "tag-list": [{"count": "1", "name": "has german audiobooks"}],
            },
            {
                "id": "dd5f8909-245d-458b-833a-cd6b698399ce",
                "type": "Person",
                "ext:score": "36",
                "name": "Richard Swift",
                "sort-name": "Swift, Richard",
                "gender": "male",
                "country": "US",
                "area": {
                    "id": "489ce91b-6658-3307-9877-795b68554c98",
                    "type": "Country",
                    "name": "United States",
                    "sort-name": "United States",
                    "life-span": {"ended": "false"},
                },
                "begin-area": {
                    "id": "ae0110b6-13d4-4998-9116-5b926287aa23",
                    "type": "Subdivision",
                    "name": "California",
                    "sort-name": "California",
                    "life-span": {"ended": "false"},
                },
                "end-area": {
                    "id": "ced2611f-cfac-438a-95d0-02d6f5fb4f84",
                    "type": "City",
                    "name": "Tacoma",
                    "sort-name": "Tacoma",
                    "life-span": {"ended": "false"},
                },
                "ipi-list": ["00438859899"],
                "life-span": {
                    "begin": "1977-03-16",
                    "end": "2018-07-03",
                    "ended": "true",
                },
                "alias-list": [
                    {
                        "sort-name": "Swift-Ochoa, Ricardo Sigilfredo Olivarez",
                        "type": "Legal name",
                        "alias": "Ricardo Sigilfredo Olivarez Swift-Ochoa",
                    }
                ],
            },
        ],
        "artist-count": 2184,
    }


@pytest.fixture
def musicbrainzngs_result():
    return set(
        [
            "Pop",
            "Country",
            "Electropop",
            "Female Vocals",
            "Dance-Pop",
            "Pop Rock",
            "Country Pop",
            "Contemporary Country",
            "Teen Pop",
            "Top 40",
            "Country-Pop",
            "Taylor-Swift",
            "Singer/Songwriter",
            "Fixme Label Mess",
            "Hp",
        ]
    )


@pytest.fixture
def tag_provider() -> MusicBrainzgsTagProvider:
    return MusicBrainzgsTagProvider()


@pytest.fixture
def artist():
    return "Taylor Swift"


def test_get_tags(
    mocker, artist, tag_provider, musicbrainzngs_response, musicbrainzngs_result
):
    musicbrainz_patch = mocker.patch(
        "llame.tag_providers.musicbrainzngs_.musicbrainzngs.search_artists"
    )
    musicbrainz_patch.return_value = musicbrainzngs_response

    result = tag_provider.get_tags_for(artist)
    assert set(result) == musicbrainzngs_result
